package common;

public enum Operation {
	GET_DATES_OF_REPORTS,
	GET_PARKING_REPORT,
	GET_PARKING_AVAILABILITY,
	REGISTER_SUBSCRIBER,
	EXTEND_PARKING,
	GET_DETAILS_OF_ACTIVE_INFO,
	GET_ACTIVE_PARKINGS,
	GET_ALL_SUBSCRIBERS,
	FORGEOT_MY_PARKING_CODE,
	UPDATE_PARKING_HISTORY_OF_SUBSCRIBER,
	DELETE_ORDER,
	ASK_FOR_RESERVATIONS,
	SUBSCRIBER_DETAILS,
	COLLECT_CAR,
	VALIDATE_SUBSCRIBER_BY_TAG,
	VALIDATE_SUBSCRIBER_BY_SUBSCRIBER_CODE,
	LOGIN,
	CHECK_AVAILABILITY_FOR_ORDER,
	ADD_NEW_ORDER,
	DISCONNECT,
	GET_SUBSCRIBER_STATUS_REPORT
}
