package common;

public enum Operation {
	GET_DATES_OF_REPORTS,
	GET_PARKING_REPORT,
	GET_PARKING_AVAILABILITY,
	REGISTER_SUBSCRIBER,
	EXTEND_PARKING,
	GET_DETAILS_OF_ACTIVE_INFO,
	GET_ACTIVE_PARKINGS,
	GET_ALL_SUBSCRIBERS,
	FORGEOT_MY_PARKING_CODE,
	UPDATE_PARKING_HISTORY_OF_SUBSCRIBER,
	DELETE_ORDER,
	ASK_FOR_RESERVATIONS,
	SUBSCRIBER_DETAILS,
	COLLECT_CAR,
	VALIDATE_SUBSCRIBER_BY_TAG,
	VALIDATE_SUBSCRIBER_BY_SUBSCRIBER_CODE,
	LOGIN,
	CHECK_AVAILABILITY_FOR_ORDER,
	ADD_NEW_ORDER,
	DISCONNECT,
	GET_SUBSCRIBER_STATUS_REPORT,
	IS_THERE_AN_EXISTED_ORDER,
	SUBSCRIBER_EXISTS, //what is the difference between this and VALIDATE_SUBSCRIBER_BY_SUBSCRIBER_CODE?
	TAG_EXISTS, //what is the difference between this and VALIDATE_SUBSCRIBER_BY_TAG?
	SUBSCRIBER_ALREADY_ENTERED,
	TAG_ID_ALREADY_ENTERED,
	FIND_MATCHED_SUBSCRIBER_TO_THE_TAG,
	DELIVERY_VIA_RESERVATION,
	IS_THERE_FREE_PARKING_SPACE,
	GET_VEHICLE_ID,
	DELIVER_VEHICLE,
	CHECK_IF_THERE_IS_RERSERVATION
	}
